

<html>
<head>
<title>Catch</title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="../static/theme.css" rel="stylesheet" type="text/css" />
<script src="../static/content.js" type="text/javascript"></script>
</head>
<body>

<h1>Catch <span class="ver">[v1.1.04+]</span></h1>

<p><a href="Try.htm">try</a>서술문의 실행 중에 예외가 일어나면 실행할 코드를 지정합니다.</p>

<pre class="Syntax" style="line-height: 120%">Catch [, OutputVar]
    <i>Statement</i></pre>
<pre class="Syntax" style="line-height: 100%">Catch [, OutputVar]
{
    <i>Statements</i>
}</pre>
<h3>매개변수</h3>
<dl>

  <dt>OutputVar</dt>
  <dd><p><em>(선택적)</em> 예외의 값을 저장할 변수의 이름.</p></dd>

  <dt><i>Statement(s)</i></dt>
  <dd><p>예외가 일어나면 실행할 명령어 또는 표현식.</p></dd>

</dl>

<h3>논평</h3>
<p>
<em>catch</em>가 사용되면 바로 위 <a href="Try.htm">try</a> 서술문에 종속됩니다. <em>catch</em>는 언제나 바로 위 가장 가까운 <em>try</em> 서술문에 속합니다. 단, <a href="Block.htm">블록</a>을 사용하여 그 행위를 바꿀 수 있습니다.</p>
<p>
<a href="Block.htm#otb">One True Brace (OTB) 스타일</a>을 선택적으로 사용할 수 있습니다. 예를 들어:</p>
<pre>try <strong>{</strong>
    ...
<strong>}</strong> catch e <strong>{</strong>
    ...
<strong>}</strong></pre>

<h3 id="RuntimeErrors">실행시간 에러</h3>
<p>
<em>try-catch</em> 서술문은 실행 시간 에러를 처리하는 데에도 사용할 수 있습니다. 두 가지 종류의 실행시간 에러가 있습니다: 보통 <a href="../misc/ErrorLevel.htm">ErrorLevel</a>을 설정하는 에러와, 보통 에러 메시지를 보여준 후에 현재 쓰레드를 종료시키는 에러가 있습니다. 적재시간 에러는 처리가 불가능합니다. 왜냐하면 <em>try</em> 서술문이 실행되기 전에 일어나기 때문입니다. 하위 호환을 위해 (그리고 어떤 경우는 편의를 위해), 실행시간 에러는 <em>try</em> 블록이 실행되는 동안 오직 예외만 던집니다. 대부분의 명령어는 <em>try-catch</em>의 사용을 지원합니다; 그렇지만, <a href="../misc/ErrorLevel.htm">ErrorLevel</a>은 명령어가 성공하면 여전히 0으로 설정됩니다.</p>
<p>
<em>OutputVar</em>에 저장된 값은 (존재하면) <a href="Throw.htm#Exception">예외 객체</a>입니다.</p>

<h3>관련 항목</h3>
<p><a href="Try.htm">Try</a>, <a href="Throw.htm">Throw</a>, <a href="Finally.htm">Finally</a>, <a href="Block.htm">Blocks</a></p>
<h3>예제</h3>
<p><a href="Try.htm#Examples">Try</a> 참조.</p>

</body>
</html>
